export const GET_ALL_PRODUCTS_LOADING = "GET_ALL_PRODUCTS_LOADING";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";

export const ADD_PRODUCT_LOADING = "ADD_PRODUCT_LOADING";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const UPDATE_PRODUCT_LOADING = "UPDATE_PRODUCT_LOADING";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";

export const DELETE_PRODUCT_LOADING = "DELETE_PRODUCT_LOADING";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export const PRODUCTS_FIELDS_CHANGE = "PRODUCTS_FIELDS_CHANGE";

export const ADD_PRODUCT_STATE_ON_LOAD = "ADD_PRODUCT_STATE_ON_LOAD";
export const UPDATE_PRODUCT_STATE_ON_LOAD = "UPDATE_PRODUCT_STATE_ON_LOAD";
export const DELETE_PRODUCT_STATE_ON_LOAD = "DELETE_PRODUCT_STATE_ON_LOAD";

export const SET_PRODUCT_VIEWED = "SET_PRODUCT_VIEWED";

export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const SET_LOADING = "SET_LOADING";
