export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTERED_STATE_ON_LOAD = "REGISTERED_STATE_ON_LOAD";

export const LOGIN_lOADING = "LOGIN_lOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_STATE_ON_LOAD = "LOGIN_STATE_ON_LOAD";
export const LOAD_USER = "LOAD_USER";

export const LOGOUT = "LOGOUT";
